
# Values 'xxxxx' need to be overwritten!

server:
  port: 9014

auth.jwt.secret: ZGV2X3NlY3JldA==  # Base64: dev_secret

spring:

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2.console:
    enabled: true
    settings:
      web-allow-others: true
  
  # This generates a sql file from all hibernate annotations
  # jpa.properties.javax.persistence.schema-generation.scripts.action: create
  # jpa.properties.javax.persistence.schema-generation.scripts.create-target: target/hibernate-code-generation.sql
  # jpa.properties.javax.persistence.schema-generation.scripts.create-source: metadata
  
  # Old GMail config
  # mail: 
  #   host: smtp.gmail.com
  #   port: 587
  #   username: xxxxx@gmail.com 
  #   password: xxxxx
  #   properties:
  #     mail.smtp:
  #       auth: true
  #       connectiontimeout: 5000
  #       timeout: 5000
  #       writetimeout: 5000
  #       starttls.enable: true
  #       ssl.trust: smtp.gmail.com
        
  mail: 
    host: mail.hukot.net
    port: 587
    username: xxxxx@grenc.eu
    password: xxxxx
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls.enable: true
          ssl.trust: mail.hukot.net
  
host:
   address: 
      verification: http://localhost:4014/potrditev
      wish: http://localhost:4014/pismo

template-data:
  admin: Kekec
  admin-email: kekec@hosta.com
  giver: Rožle
  giver-email: rozle@hosta.com
  receiver: Mojca
  receiver-email: mojca@hosta.com
  wish: <p>Mir na svetu!</p>