server:
  port: 9000
  
spring: 
  mail: 
    host: smtp.gmail.com
    port: 587
    username: mesano.darilo@gmail.com 
    password: invalidpassword
    properties:
      mail.smtp:
        auth: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
        starttls.enable: true
  
storage:
  wish:
    folder: C:\\Users\\Nejc\\Development\\Projects\\GiftMixer\\files\\wish
  users:
    file: C:\\Users\\Nejc\\Development\\Projects\\GiftMixer\\files\\users.txt