
# Values 'xxxxx' need to be overwritten!

server:
  port: 9014

auth.jwt.secret: ZGV2X3NlY3JldA==  # Base64: dev_secret

spring:

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2.console.enabled: true
  
  mail: 
    host: smtp.gmail.com
    port: 587
    username: xxxxx@gmail.com 
    password: xxxxx
    properties:
      mail.smtp:
        auth: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
        starttls.enable: true
  
  
storage:
  wish:
    folder: xxxxx
  users:
    file: xxxxx
host.address.darilo: http://localhost:4204/darilo

